[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "(js|javascript)"
file-types = ["js", "mjs", "cjs"]
shebangs = ["node"]
roots = []
comment-token = "//"
# TODO: highlights-params
language-server = { command = "typescript-language-server", args = ["--stdio"], language-id = "javascript" }
indent = { tab-width = 2, unit = "  " }
auto-format = true
# formatter = { command = "eslint", args = ["--stdin"] }

[[language]]
name = "jsx"
scope = "source.jsx"
injection-regex = "jsx"
file-types = ["jsx"]
roots = []
comment-token = "//"
language-server = { command = "typescript-language-server", args = ["--stdio"], language-id = "javascriptreact" }
indent = { tab-width = 2, unit = "  " }
grammar = "javascript"
auto-format = true
# formatter = { command = "eslint", args = ["--stdin"] }

[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "(ts|typescript)"
file-types = ["ts"]
shebangs = []
roots = []
# TODO: highlights-params
language-server = { command = "typescript-language-server", args = ["--stdio"], language-id = "typescript"}
indent = { tab-width = 2, unit = "  " }
auto-format = true
# formatter = { command = "eslint", args = ["--stdin"] }

[[grammar]]
name = "typescript"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript", rev = "6aac031ad88dd6317f02ac0bb27d099a553a7d8c", subpath = "typescript" }

[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "(tsx)" # |typescript
file-types = ["tsx"]
roots = []
# TODO: highlights-params
language-server = { command = "typescript-language-server", args = ["--stdio"], language-id = "typescriptreact" }
indent = { tab-width = 2, unit = "  " }
auto-format = true
# formatter = { command = "eslint", args = ["--stdin"] }

[[grammar]]
name = "tsx"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript", rev = "6aac031ad88dd6317f02ac0bb27d099a553a7d8c", subpath = "tsx" }

[[language]]
name = "rust"
indent = { tab-width = 2, unit = "  " }
file-types = ["rs"]

[language.config]
checkOnSave = { command = "clippy" }

# [[language]]
# name = "toml"
# injection-regex = "toml"
# file-types = ["toml"]
# roots = []
# comment-token = "#"
# language-server = { command = "taplo", args = ["lsp", "stdio"] }
# indent = { tab-width = 2, unit = "  " }

# [[grammar]]
# name = "toml"
# source = { git = "https://github.com/ikatyang/tree-sitter-toml", rev = "7cff70bbcbbc62001b465603ca1ea88edd668704" }
